openapi: 3.0.0
info:
  title: Chat Service API
  description: API for interacting with a chat service
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /auth/allusers/{id}:
    get:
      summary: Get all users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '404':
          description: Not Found
  /auth/setavatar/{id}:
    post:
      summary: Set avatar for a user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AvatarRequest'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /auth/logout/{id}:
    get:
      summary: User logout
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /messages/addmsg/:
    post:
      summary: Add a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /messages/getmsg/:
    post:
      summary: Get messages
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '400':
          description: Bad Request
  /ping:
    get:
      summary: Ping endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                example:
                  msg: Ping Successful
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    AvatarRequest:
      type: object
      properties:
        avatarUrl:
          type: string
      required:
        - avatarUrl
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        avatarUrl:
          type: string
      required:
        - id
        - username
    Message:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        sender:
          type: string
        receiver:
          type: string
      required:
        - id
        - text
        - sender
        - receiver